### ISSUE TITLE
如何获取文件下载地址？

### ISSUE THREAD

**Issue by hug2008** [hongliuliao/ehttp#10]
客户端上传完文件后，服务端如何返回文件下载地址呢？

**Comment by hongliuliao** [comment]
可以参考这里的实现: https://github.com/hongliuliao/ehttp/blob/master/test/issue5/issue5_server.cpp
上传完文件后, 具体文件保存在什么地方, 需要用户自己确定, 之后参考response_file的实现, 读取文件, 并返回给客户端

**Comment by hug2008** [comment]
谢谢

**Comment by hongliuliao** [comment]
另外我写了一个简单上传/下载的例子, 可以参考一下: https://github.com/hongliuliao/ehttp/blob/master/test/http_multipart_demo.cpp
