### ISSUE TITLE
如何添加 response 头信息，比如 cookie

### ISSUE THREAD

**Issue by gooking** [hongliuliao/ehttp#13]
如何添加 response 头信息，比如 cookie、User-Agent 等信息？

我看有其他的组件会这么写：

![image](https://user-images.githubusercontent.com/7286469/53235894-dfa77500-36cd-11e9-863d-45aa6a5f2d95.png)

请问你们有支持么？

**Comment by hongliuliao** [comment]
支持的, response 对象有set_header(name, value) 方法: 可以参考https://github.com/hongliuliao/ehttp/blob/master/test/http_server_test.cpp 的usleep方法

**Comment by gooking** [comment]
谢谢，问题解决
