### ISSUE TITLE
ajax跨域，需要支持除了 GET，POST 之外的 option 支持

### ISSUE THREAD

**Issue by gooking** [hongliuliao/ehttp#14]
ajax跨域，需要支持除了 GET，POST 之外的 option 支持

请问如果支持 option 请求呢，不需要返回任何实际数据，只要能返回 200 的httpstatus 状态码即可

**Comment by hongliuliao** [comment]
已经添加对 OPTIONS的支持, 例子参考: https://github.com/hongliuliao/ehttp/blob/master/test/http_server_test.cpp 中的options_test方法

**Comment by gooking** [comment]
问题解决，给力！
