### ISSUE TITLE
Possible Mac OS compatibility?

### ISSUE THREAD

**Issue by Xilun-Chen** [hongliuliao/ehttp#15]
Hi 

The current version looks great, but it only compiles on Linux machines, is it possible to add Mac OSX support which use Kqueue?

Thanks

**Comment by hongliuliao** [comment]
Sorry，ehttp have no plan to support maxos. If you want to do that，the project restbed: https://github.com/Corvusoft/restbed may be a better choose.

**Comment by robromano** [comment]
Also see Drogon: A C++14/17 based HTTP web application framework running on Linux/macOS/Unix https://github.com/an-tao/drogon
