### ISSUE TITLE
服务端没有默认设置超时时间吗

### ISSUE THREAD

**Issue by zhanb** [hongliuliao/ehttp#17]
刚刚试了下，服务端好像没有默认设置超时时间？那么对方大量建立长连接服务不就没法工作了？

**Comment by hongliuliao** [comment]
链接过多通常来说有如下两种情况
1. 链接泄露: 客户端因为代码等问题导致链接没有及时释放
2. 请求过载: 因为请求数超过服务器端承载能力导致服务过载，进而连接数过多

链接过多问题需要通过过载保护手段进行处理，此功能会后续的功能迭代中完成，时间点预计在Q2

**Comment by zhanb** [comment]
你说的那两种情况还好，就怕是遇到恶意攻击，攻击方一直发连接，不解决这个问题这个代码就只能当个demo,没办法实用。我也有关注restbed,他那个应该是默认5s超时，过5s就强行把连接关闭了，这个时间还可以自己设置。

**Comment by hongliuliao** [comment]
ehttp现在定位是用于微服务的, 所以, 像攻击这类安全问题, 是需要在对外接入的nginx层, 或者用sidecar(如envoy)解决

**Comment by hongliuliao** [comment]
已支持客户端最大空闲时间设置, 通过set_client_max_idle_time函数

**Comment by zhanb** [comment]
给力
