### ISSUE TITLE
add_mapping等几个疑问

### ISSUE THREAD

**Issue by suneliw** [hongliuliao/ehttp#23]
@hongliuliao 你好，我又来了，有几个疑问请教你：
1、http_server.add_mapping()方法有3个重载，区别在于第二个参数，有method_handler_ptr、json_handler_ptr、HttpJsonHandler，这几个有什么设计用意吗？
2、有没有方法在add_mapping()的时候加上我们的自定义参数传递？
3、有些静态资源文件比如图片等能不能实现直接访问？
希望不吝赐教，非常感谢！

**Comment by hongliuliao** [comment]
1. method_handler_ptr 针对的是你希望灵活的控制返回响应的时候使用, json_handler_ptr和HttpJsonHandler都是返回json格式的响应, 区别只是在于一个是使用函数指针, 一个是使用类
2. 这是在什么情况下有这个需求?
3. 可以实现, 具体参考: https://github.com/hongliuliao/ehttp/blob/master/test/issue5/issue5_server.cpp 中的 /test/issue5/issue5.html 处理方法

**Comment by suneliw** [comment]
第二种情况是这样的，有些配置是通过配置文件读进来的，现在要么每个请求都去读一次配置，要么用全局变量。如果可以传递自定义参数的话就好些。
第三种情况需要配置路由，也就是通过add_mapping()添加，这种只适合已知路径且是固定的，是吧？

**Comment by hongliuliao** [comment]
第二种情况: 可以使用 HttpJsonHandler 的方式, 把配置信息放到 Handler 对象中
第三种情况: 现在只支持固定路径, 这个主要是考虑效率

**Comment by suneliw** [comment]
好的，我试一下。第三种变通方式是固定路径，文件名通过参数来改变，应该可行。
