### ISSUE TITLE
处理写的为什么不用多线程？

### ISSUE THREAD

**Issue by huifeidexingyuner** [hongliuliao/ehttp#24]
处理写的为什么不用多线程？

**Comment by hongliuliao** [comment]
因为现在的用户处理函数(handler) 是在读事件的时候触发的, 而用户的处理函数耗时可能比较高, 所以, 在处理读的时候, 使用了多线程.

**Comment by huifeidexingyuner** [comment]
> 因为现在的用户处理函数(handler) 是在读事件的时候触发的, 而用户的处理函数耗时可能比较高, 所以, 在处理读的时候, 使用了多线程.

下游客户端网速慢这种情况，写也做成多线程很有必要吧？

**Comment by hongliuliao** [comment]
> > 因为现在的用户处理函数(handler) 是在读事件的时候触发的, 而用户的处理函数耗时可能比较高, 所以, 在处理读的时候, 使用了多线程.
> 
> 下游客户端网速慢这种情况，写也做成多线程很有必要吧？

epoll是基于事件触发的, 如果下游网速慢, 并不会阻塞服务, 类似redis是单线程处理读&写事件, 但是不会因为客户端网络慢影响redis自身的性能

**Comment by huifeidexingyuner** [comment]
> > > 因为现在的用户处理函数(handler) 是在读事件的时候触发的, 而用户的处理函数耗时可能比较高, 所以, 在处理读的时候, 使用了多线程.
> > 
> > 
> > 下游客户端网速慢这种情况，写也做成多线程很有必要吧？
> 
> epoll是基于事件触发的, 如果下游网速慢, 并不会阻塞服务, 类似redis是单线程处理读&写事件, 但是不会因为客户端网络慢影响redis自身的性能

举个例子吧，比如a客户端发送了一个请求，ehttp被给a的响应阻塞住了；这时候b的请求又来了被解析完成，准备响应b，但是这时ehttp被a的写响应阻塞住了，没法及时给b响应。这种情况存在吗？

**Comment by hongliuliao** [comment]
> > > > 因为现在的用户处理函数(handler) 是在读事件的时候触发的, 而用户的处理函数耗时可能比较高, 所以, 在处理读的时候, 使用了多线程.
> > > 
> > > 
> > > 下游客户端网速慢这种情况，写也做成多线程很有必要吧？
> > 
> > 
> > epoll是基于事件触发的, 如果下游网速慢, 并不会阻塞服务, 类似redis是单线程处理读&写事件, 但是不会因为客户端网络慢影响redis自身的性能
> 
> 举个例子吧，比如a客户端发送了一个请求，ehttp被给a的响应阻塞住了；这时候b的请求又来了被解析完成，准备响应b，但是这时ehttp被a的写响应阻塞住了，没法及时给b响应。这种情况存在吗？

不会的, 事件触发的意思就是, 只有a的网络句柄可写了, 才会触发可写事件, 如果a这个时候因为网络等原因阻塞了, 可写事件是不会触发的. 所以, 发送给a/b客户端内容的时候, 其实是可能交错着的, 一段时间发给a一部分, 一段时间给b一部分.

**Comment by huifeidexingyuner** [comment]
> > > > > 因为现在的用户处理函数(handler) 是在读事件的时候触发的, 而用户的处理函数耗时可能比较高, 所以, 在处理读的时候, 使用了多线程.
> > > > 
> > > > 
> > > > 下游客户端网速慢这种情况，写也做成多线程很有必要吧？
> > > 
> > > 
> > > epoll是基于事件触发的, 如果下游网速慢, 并不会阻塞服务, 类似redis是单线程处理读&写事件, 但是不会因为客户端网络慢影响redis自身的性能
> > 
> > 
> > 举个例子吧，比如a客户端发送了一个请求，ehttp被给a的响应阻塞住了；这时候b的请求又来了被解析完成，准备响应b，但是这时ehttp被a的写响应阻塞住了，没法及时给b响应。这种情况存在吗？
> 
> 不会的, 事件触发的意思就是, 只有a的网络句柄可写了, 才会触发可写事件, 如果a这个时候因为网络等原因阻塞了, 可写事件是不会触发的. 所以, 发送给a/b客户端内容的时候, 其实是可能交错着的, 一段时间发给a一部分, 一段时间给b一部分.

多谢！

**Comment by huifeidexingyuner** [comment]
> > > > > > 因为现在的用户处理函数(handler) 是在读事件的时候触发的, 而用户的处理函数耗时可能比较高, 所以, 在处理读的时候, 使用了多线程.
> > > > > 
> > > > > 
> > > > > 下游客户端网速慢这种情况，写也做成多线程很有必要吧？
> > > > 
> > > > 
> > > > epoll是基于事件触发的, 如果下游网速慢, 并不会阻塞服务, 类似redis是单线程处理读&写事件, 但是不会因为客户端网络慢影响redis自身的性能
> > > 
> > > 
> > > 举个例子吧，比如a客户端发送了一个请求，ehttp被给a的响应阻塞住了；这时候b的请求又来了被解析完成，准备响应b，但是这时ehttp被a的写响应阻塞住了，没法及时给b响应。这种情况存在吗？
> > 
> > 
> > 不会的, 事件触发的意思就是, 只有a的网络句柄可写了, 才会触发可写事件, 如果a这个时候因为网络等原因阻塞了, 可写事件是不会触发的. 所以, 发送给a/b客户端内容的时候, 其实是可能交错着的, 一段时间发给a一部分, 一段时间给b一部分.
> 
> 多谢！

有没有另一种情况a和b可以同时写？

**Comment by huifeidexingyuner** [comment]
> > > > > 因为现在的用户处理函数(handler) 是在读事件的时候触发的, 而用户的处理函数耗时可能比较高, 所以, 在处理读的时候, 使用了多线程.
> > > > 
> > > > 
> > > > 下游客户端网速慢这种情况，写也做成多线程很有必要吧？
> > > 
> > > 
> > > epoll是基于事件触发的, 如果下游网速慢, 并不会阻塞服务, 类似redis是单线程处理读&写事件, 但是不会因为客户端网络慢影响redis自身的性能
> > 
> > 
> > 举个例子吧，比如a客户端发送了一个请求，ehttp被给a的响应阻塞住了；这时候b的请求又来了被解析完成，准备响应b，但是这时ehttp被a的写响应阻塞住了，没法及时给b响应。这种情况存在吗？
> 
> 不会的, 事件触发的意思就是, 只有a的网络句柄可写了, 才会触发可写事件, 如果a这个时候因为网络等原因阻塞了, 可写事件是不会触发的. 所以, 发送给a/b客户端内容的时候, 其实是可能交错着的, 一段时间发给a一部分, 一段时间给b一部分.

如果ehttp支持多个监听socket，就要支持多个线程写吧？

**Comment by huifeidexingyuner** [comment]
> > > > > 因为现在的用户处理函数(handler) 是在读事件的时候触发的, 而用户的处理函数耗时可能比较高, 所以, 在处理读的时候, 使用了多线程.
> > > > 
> > > > 
> > > > 下游客户端网速慢这种情况，写也做成多线程很有必要吧？
> > > 
> > > 
> > > epoll是基于事件触发的, 如果下游网速慢, 并不会阻塞服务, 类似redis是单线程处理读&写事件, 但是不会因为客户端网络慢影响redis自身的性能
> > 
> > 
> > 举个例子吧，比如a客户端发送了一个请求，ehttp被给a的响应阻塞住了；这时候b的请求又来了被解析完成，准备响应b，但是这时ehttp被a的写响应阻塞住了，没法及时给b响应。这种情况存在吗？
> 
> 不会的, 事件触发的意思就是, 只有a的网络句柄可写了, 才会触发可写事件, 如果a这个时候因为网络等原因阻塞了, 可写事件是不会触发的. 所以, 发送给a/b客户端内容的时候, 其实是可能交错着的, 一段时间发给a一部分, 一段时间给b一部分.

那你觉得nginx多进程的写是没必要的？

**Comment by huifeidexingyuner** [comment]
> > > > > > 因为现在的用户处理函数(handler) 是在读事件的时候触发的, 而用户的处理函数耗时可能比较高, 所以, 在处理读的时候, 使用了多线程.
> > > > > 
> > > > > 
> > > > > 下游客户端网速慢这种情况，写也做成多线程很有必要吧？
> > > > 
> > > > 
> > > > epoll是基于事件触发的, 如果下游网速慢, 并不会阻塞服务, 类似redis是单线程处理读&写事件, 但是不会因为客户端网络慢影响redis自身的性能
> > > 
> > > 
> > > 举个例子吧，比如a客户端发送了一个请求，ehttp被给a的响应阻塞住了；这时候b的请求又来了被解析完成，准备响应b，但是这时ehttp被a的写响应阻塞住了，没法及时给b响应。这种情况存在吗？
> > 
> > 
> > 不会的, 事件触发的意思就是, 只有a的网络句柄可写了, 才会触发可写事件, 如果a这个时候因为网络等原因阻塞了, 可写事件是不会触发的. 所以, 发送给a/b客户端内容的时候, 其实是可能交错着的, 一段时间发给a一部分, 一段时间给b一部分.
> 
> 那你觉得nginx多进程的写是没必要的？
for (int i = 0; i < fds_num; i++) {
            this->handle_event(events[i]);
        }这块是个循环，如果a的写比较慢，就会阻塞住循环，影响b的写？如果多个线程是不是就没这个问题？

**Comment by hongliuliao** [comment]
epoll是是非阻塞io, 也就是说, 调用send的时候, 并不会阻塞, 如果写不了, 也会立刻返回, 并设置errno为EAGAIN

**Comment by huifeidexingyuner** [comment]
> epoll是是非阻塞io, 也就是说, 调用send的时候, 并不会阻塞, 如果写不了, 也会立刻返回, 并设置errno为EAGAIN

这个说法是对的，但是有些场景是要写多线程的。 再举个例子，比如响应包需要做各种处理之后再发给客户端比如gzip等处理，这样的话写是多线程非常必要吧？

**Comment by hongliuliao** [comment]
> > epoll是是非阻塞io, 也就是说, 调用send的时候, 并不会阻塞, 如果写不了, 也会立刻返回, 并设置errno为EAGAIN
> 
> 这个说法是对的，但是有些场景是要写多线程的。 再举个例子，比如响应包需要做各种处理之后再发给客户端，比如gzip等处理，这样的话写是多线程非常必要吧？

是的, 如果在处理写事件的时候, 还有其他耗时的操作, 比如gzip压缩, 就需要使用多线程

**Comment by huifeidexingyuner** [comment]
> > > epoll是是非阻塞io, 也就是说, 调用send的时候, 并不会阻塞, 如果写不了, 也会立刻返回, 并设置errno为EAGAIN
> > 
> > 
> > 这个说法是对的，但是有些场景是要写多线程的。 再举个例子，比如响应包需要做各种处理之后再发给客户端，比如gzip等处理，这样的话写是多线程非常必要吧？
> 
> 是的, 如果在处理写事件的时候, 还有其他耗时的操作, 比如gzip压缩, 就需要使用多线程

嗯。
