### ISSUE TITLE
g_client_id如果超过上限呢?

### ISSUE THREAD

**Issue by huifeidexingyuner** [hongliuliao/ehttp#25]
g_client_id如果超过上限呢?

**Comment by hongliuliao** [comment]
long 型的最大值是 9223372036854775807, 假设ehttp的QPS能达到5万, 则溢出的时间需要 9223372036854775807L / 50000 / 3600 / 24 / 365 = 584万年

**Comment by huifeidexingyuner** [comment]
> long 型的最大值是 9223372036854775807, 假设ehttp的QPS能达到5万, 则溢出的时间需要 9223372036854775807L / 50000 / 3600 / 24 / 365 = 584万年

也是

**Comment by huifeidexingyuner** [comment]
> > long 型的最大值是 9223372036854775807, 假设ehttp的QPS能达到5万, 则溢出的时间需要 9223372036854775807L / 50000 / 3600 / 24 / 365 = 584万年
> 
> 也是

目前这个项目面向的最高qps是多少？未来会不会发展到10亿qps？

**Comment by hongliuliao** [comment]
> > > long 型的最大值是 9223372036854775807, 假设ehttp的QPS能达到5万, 则溢出的时间需要 9223372036854775807L / 50000 / 3600 / 24 / 365 = 584万年
> > 
> > 
> > 也是
> 
> 目前这个项目面向的最高qps是多少？未来会不会发展到10亿qps？

与redis的性能是一个量级就行, 通常不会超过10万

**Comment by huifeidexingyuner** [comment]
> > > > long 型的最大值是 9223372036854775807, 假设ehttp的QPS能达到5万, 则溢出的时间需要 9223372036854775807L / 50000 / 3600 / 24 / 365 = 584万年
> > > 
> > > 
> > > 也是
> > 
> > 
> > 目前这个项目面向的最高qps是多少？未来会不会发展到10亿qps？
> 
> 与redis的性能是一个量级就行, 通常不会超过10万, 当前的测试性能可以参考README.md中的结果

如果是一个城市的大脑，还是希望一代又一代的运行下去，永不停歇。
