### ISSUE TITLE
为什么add_client(epoll_context);要加互斥锁？

### ISSUE THREAD

**Issue by huifeidexingyuner** [hongliuliao/ehttp#26]
int EpollSocket::add_client(EpollContext *ctx) {
    pthread_mutex_lock(&_client_lock);
    _clients++;
    _eclients[ctx->_id] = ctx;
    pthread_mutex_unlock(&_client_lock);
    return 0;
}
这段代码不涉及到多线程情况，为什么要加锁？

**Comment by hongliuliao** [comment]
是否加锁要看对于共享变量(_client/_eclients)的所有操作, 而不是只看单个函数是否是单线程访问的, 比如remove_client会对_clients进行减操作, 而 remove_client 可能在另外的线程

**Comment by huifeidexingyuner** [comment]
> 是否加锁要看对于共享变量(_client/_eclients)的所有操作, 而不是只看单个函数是否是单线程访问的, 比如remove_client会对_clients进行减操作, 而 remove_client 可能在另外的线程

ok
