### ISSUE TITLE
什么样的情况能走到第二个分支？能举个例子吗？

### ISSUE THREAD

**Issue by huifeidexingyuner** [hongliuliao/ehttp#27]
if (req->_last_was_value) { 
        req->_header_fields.push_back(field);
        req->_last_was_value = false;
    } else {
        req->_header_fields[req->_header_fields.size() - 1] += field;
    }

正常都是走第一个分支吧？

**Comment by hongliuliao** [comment]
已添加注释, 因为从网络句柄中读取的数据是流式的, 所以, 一次读取可能读取到一半的数据, 举个例子:
"Content-length: 14": 这是一个完整的header, Content-length 是field, 14是value
这时有可能一次从网络中只读取了 "Content-", 再读取一次的时候读取到了"length", 所以, 第一次, 需要把field 加到集合中去(_header_fields.push_back(field)), 而第二次, 需要追加内容.

**Comment by huifeidexingyuner** [comment]
> 已添加注释, 因为从网络句柄中读取的数据是流式的, 所以, 一次读取可能读取到一半的数据, 举个例子:
> "Content-length: 14": 这是一个完整的header, Content-length 是field, 14是value
> 这时有可能一次从网络中只读取了 "Content-", 再读取一次的时候读取到了"length", 所以, 第一次, 需要把field 加到集合中去(_header_fields.push_back(field)), 而第二次, 需要追加内容.

ok
