### ISSUE TITLE
CMake Support

### ISSUE THREAD

**Issue by webfolderio** [hongliuliao/ehttp#28]
Hi,

Although Makefile is fine a project with minimal dependency CMake is nice to have feature.
Do you have plan to add CMake support.

Thanks

**Comment by hongliuliao** [comment]
Sorry, there is no plan to support CMAKE, The reasons are as follows:

1. The principle of this project is "keep simple", so i want't include many dependencies.
2. The feature of CMake is cross-platform and generate makefile, but ehttp is support linux only(base on epoll) and current makefile is not complexly enough to use CMake.
