### ISSUE TITLE
每个请求的上下文释放都是在on_writeable之后完成的吗？

### ISSUE THREAD

**Issue by huifeidexingyuner** [hongliuliao/ehttp#29]
int ret = socket_handler.on_writeable(*epoll_context);
    if(ret == WRITE_CONN_CLOSE) {
        return close_and_release(event);
    }

**Comment by hongliuliao** [comment]
不一定, 可以搜索一下调用 close_and_release 的方法, 另外如果是长连接的话, 会在HttpEpollWatcher中清空request & response的内容
