### ISSUE TITLE
spurious wakeup？

### ISSUE THREAD

**Issue by huifeidexingyuner** [hongliuliao/ehttp#30]
void* ThreadPool::execute_thread() {
    Task *task;
    
    while(true) {
        ...............................................................................................
        m_task_mutex.lock();

   
        while ((m_pool_state != STOPPED) && (m_tasks.empty())) {
            m_task_cond_var.wait(m_task_mutex.get_mutex_ptr());
            
        }
        .....................................................................................................
        task = m_tasks.front();
        m_tasks.pop_front();
        
        m_task_mutex.unlock();

        // execute the task
        .................................................................................
    }
   
}
互斥区域就一个线程能进来，怎么会出现虚假唤醒？如果while改成if也没问题吧？

**Comment by hongliuliao** [comment]
调用wait之后, 锁已经释放了, 所以, 可能有多个线程进入wait状态

**Comment by huifeidexingyuner** [comment]
> 调用wait之后, 锁已经释放了, 所以, 可能有多个线程进入wait状态

不可能有多个线程进入wait吧，m_task_mutex.lock()和m_task_mutex.unlock()之间是临界区。

**Comment by hongliuliao** [comment]
调用wait之后, 会自动释放锁: 具体参考: https://linux.die.net/man/3/pthread_cond_wait

**Comment by huifeidexingyuner** [comment]
> 调用wait之后, 会自动释放锁: 具体参考: https://linux.die.net/man/3/pthread_cond_wait

看了，wait里也有释放锁。但是m_task_cond_var.signal()只能唤醒一个，broadcast才能唤醒多个。

**Comment by hongliuliao** [comment]
signal 至少唤醒一个而不是只唤醒一个, 具体参考: https://linux.die.net/man/3/pthread_cond_signal

**Comment by huifeidexingyuner** [comment]
#include<stdio.h>
#include<pthread.h>
#include<stdlib.h>
#include<unistd.h>
#include<errno.h>
#include<assert.h>
#include<signal.h>


pthread_mutex_t mutex =PTHREAD_MUTEX_INITIALIZER;
pthread_cond_t cond = PTHREAD_COND_INITIALIZER;

volatile int value = 0;

pthread_t tid;
pthread_t tid2;
pthread_t tid3;

void* thread_func(void* arg) {
    pthread_mutex_lock(&mutex);

    if (0 == value) {
    	printf("befor wait1\n");
        pthread_cond_wait(&cond, &mutex);
    }
    printf("the thread_func is finished value = %d\n", value);
    value = 0;
    pthread_mutex_unlock(&mutex);
}

void* thread_func3(void* arg) {
    pthread_mutex_lock(&mutex);

    if (0 == value) {
    	printf("befor wait2\n");
        pthread_cond_wait(&cond, &mutex);
    }
    printf("the thread_func3 is finished value = %d\n", value);
    value = 0;
    pthread_mutex_unlock(&mutex);
}

void* thread_func2(void* arg) {
    pthread_mutex_lock(&mutex);
    value = 1;
    //pthread_cond_broadcast(&cond);
    pthread_cond_signal(&cond);
    printf("the thread_func2 is finished value = %d\n", value);
    pthread_mutex_unlock(&mutex);
}

int
main(int argc, char* argv[])
{

    pthread_attr_t attr;
    assert(0 == pthread_attr_init(&attr));
    pthread_create(&tid, NULL, thread_func, NULL);
    pthread_create(&tid3, NULL, thread_func3, NULL);
    sleep(5);

    pthread_create(&tid2, NULL, thread_func2, NULL);
    pthread_join(tid2, NULL);
    pthread_join(tid, NULL);
    pthread_join(tid3, NULL);
    pthread_cond_destroy(&cond);
    pthread_attr_destroy(&attr);

}


举个例子，两个核的虚拟机，运行此程序，结果是只唤醒了一个线程。

**Comment by hongliuliao** [comment]
是的, 并不是一定触发多个, 但是我们编码的时候, 不能依赖特定的实现, 而是应该依赖规范描述

**Comment by huifeidexingyuner** [comment]
> 是的, 并不是一定触发多个, 但是我们编码的时候, 不能依赖特定的实现, 而是应该依赖规范描述

嗯 明白了
