### ISSUE TITLE
重复发送条件信号？

### ISSUE THREAD

**Issue by huifeidexingyuner** [hongliuliao/ehttp#31]
int ThreadPool::destroy_threadpool() {
    ................................................................
    m_task_cond_var.broadcast(); 

    int ret = -1;
    for (int i = 0; i < m_pool_size; i++) {
        void* result;
        ret = pthread_join(m_threads[i], &result);
      ............................................................................
        m_task_cond_var.broadcast(); 
    }
    ................................................................
    return m_tasks.size();
}
销毁线程池为何重复发送broadcast？

**Comment by hongliuliao** [comment]
嗯, 这块确实有问题, 感谢指正, 已修复
