### ISSUE TITLE
Quick questions

### ISSUE THREAD

**Issue by kylehslee** [hongliuliao/ehttp#36]
Hi Liao,

When I initialize the server and I go to http://localhost:3456/hello(or whatever), debug log shows like below.

DEBUG src/epoll_socket.cpp(178): server: got connection from 127.0.0.1
DEBUG src/epoll_socket.cpp(211): get accept socket which listen fd:6, conn_sock_fd:8
DEBUG src/epoll_socket.cpp(444): find idle client but is reading, skip it!
DEBUG src/epoll_socket.cpp(178): server: got connection from 127.0.0.1
DEBUG src/epoll_socket.cpp(211): get accept socket which listen fd:6, conn_sock_fd:9
DEBUG src/epoll_socket.cpp(444): find idle client but is reading, skip it!

why the server accepts two connections although I just go into the website only once?

**Comment by hongliuliao** [comment]
Do you access the url by a web browser? Browser will try to access /favicon.ico when it load the page.

**Comment by kylehslee** [comment]
> Do you access the url by a web browser? Browser will try to access /favicon.ico when it load the page.

Yes, I did through a web browser. I don't know what favicon is well and why that should work. Anyway, the favicon tries to connect one more secretly so it connects twice, is that correct?

**Comment by hongliuliao** [comment]
> > Do you access the url by a web browser? Browser will try to access /favicon.ico when it load the page.
> 
> Yes, I did through a web browser. I don't know what favicon is well and why that should work. Anyway, the favicon tries to connect one more secretly so it connects twice, is that correct?

Yes, you can try use command: "curl http://localhost:3456/hello" to make sure one request only connect once

**Comment by kylehslee** [comment]
Thank you for letting me know always!
