### ISSUE TITLE
localtime unthreadsafe question && some bugs fixed sugestions

### ISSUE THREAD

**Issue by kunwg** [hongliuliao/ehttp#37]
你好！
  本来打算使用这个库的，看封装的例程很简单方便。不过，简单阅读了一下源码，发现实现了日志系统。刚好我也自己实现了一个功能和代码规模和你相当的日志系统。于是对比了一下，发现有两个严重的问题，提出来给你参考一下。
  1、localtime函数非线程安全的，多线程并发会crash的，标准说法是：线程不可重入；换成localtime_r函数可以解决；
  2、日志api是需要支持多线程大并发的，这里使用互斥锁会严重降低性能的，所以并发测试关闭了日志，提升了性能也掩盖了问题1；建议你可以绕过这个同步问题，使用一个本地udp socket就可以解决的；sendto函数是多线程安全的；recvfrom和write函数一个线程即可，都不用加锁，并发量大了最多也就是丢日志报文。（当然，你也可以改进成不丢日志的可靠通信。）

**Comment by kunwg** [comment]
另外，sendto也可以避免磁盘写速度慢的问题。

**Comment by hongliuliao** [comment]
感谢反馈， localtime的问题已经修复， 第二个问题： 当前的日志组建定位还是基于简单的本地磁盘为主， 所以， 暂时不支持udp的模式
