### ISSUE TITLE
不支持多表单POST

### ISSUE THREAD

**Issue by lcalqf** [hongliuliao/ehttp#5]
multipart/form-data
input type="file" name="files" size="50"/
多个表单
input type="text" name="fileId" size="50"/
多表单提交时，解析出错

**Comment by hongliuliao** [comment]
现在确实不支持解析 multipart/form-data 类型的数据, 不过可以通过request.get_raw_string()获取到原始的数据, 自己进行解析

**Comment by hongliuliao** [comment]
已经添加对于multipart/form-data类型的支持, 具体使用方式可以参考test/issue5目录下的代码

**Comment by lcalqf** [comment]
好像不行吧，通过chrome测试 解析不对。
一个input是正确的，同时两个input ，一个text，一个file解析就错了。

**Comment by hongliuliao** [comment]
"一个input是正确的，同时两个input ，一个text，一个file解析就错了。 ", 两个input我也试了, 没发现问题, 方便提供一下你的html代码么?
"type=file时 文件名也解析不出来了。" 这个确实丢失了, 是有这个需求么?
"multipart-parser-c-master" 这个库有什么问题?

**Comment by lcalqf** [comment]
是的，type=file时，文件名取不出来，现在我是自己解析的body，判断\r\n解析出每一行，找到Content-Disposition，然后再找到名字。我的html和issue5基本一样，

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form
        action="http://xx.xx.xx.xx:xx/upload"
        method="post" enctype="multipart/form-data">
        <input type="file" name="files" size="50"/>
    <p>
        <input type="text" name="fileId" size="50"/>
    </p>
    <input type="submit" value="Upload It"/>
</form>

</body>
</html>`

关于文件上传
body头和 bodydata的分割符是 \r\n\r\n，这样的话，判断出“\r\n\r\n”后，后面的body data就是文件内容了，fwrite本地就可以生成文件。

**Comment by hongliuliao** [comment]
给RequestBody增加了get_file_items()方法, 用于获取mutilpart 类型的数据, 具体使用可以参考issue5_server.cpp的代码

**Comment by lcalqf** [comment]
Thank you so much :smile: 
多谢支持:+1:

**Comment by lcalqf** [comment]
这应该是个Buf吧？
std::string  assign  会把原来的字符串给覆盖掉，所以 FileItem::set_data  中_data保存的是最后一段数据。
应该是append吧，这样 item.get_data()获得的才是文件的全部数据。

**Comment by hongliuliao** [comment]
因为进行parse的数据是完整的， 所以， 进入回调函数的时候， 也是完整的数据了

**Comment by lcalqf** [comment]
但是item.get_data获得的不是完整数据吧，multipart为何不生成.a

**Comment by hongliuliao** [comment]
会是完整的数据， 因为这个函数在一个input字段只会被调用一次。multipart不生成.a是因为默认的Makefile里没有生成.a， 为了方便之后依赖升级， 最好不要修改原文件

**Comment by lcalqf** [comment]
当post数据比较大时，比如3-4m的文件，数据会分块发送，所以server也是分多次接收，on_readabl会调用多次，ss_on_multipart_data也会调用多次的，我打印出日志，是多次调用的，并且用assgin时，get_data写入文件也不对，改成append就可以了，可以打日志看下。

**Comment by hongliuliao** [comment]
on_readable会调用多次没错，但是ss_on_multipart_data调用次数是等于表单的字段数的（issue5.html中是3次），因为ss_on_multipart_data函数是在ss_on_message_complete函数中调用，此函数一次请求只会调用一次。你可以试着打印一下ss_on_multipart_data中的length和get_data()->size()的大小

**Comment by lcalqf** [comment]
![ehttp](https://user-images.githubusercontent.com/20102413/28200718-5b1d3b96-68a0-11e7-9d10-d9631eeee2d7.png)
![data](https://user-images.githubusercontent.com/20102413/28200768-8916256c-68a0-11e7-8f6d-4effd07858c3.png)

**Comment by hongliuliao** [comment]
嗯，问题我复现了，现在已经修复，不过这个问题导致的原因不是因为服务器端的数据接收了多次，而是因为数据本身如果有带\r\n字符的时候，multipart-parser-c这个库会调用一次on_part_data方法

**Comment by lcalqf** [comment]
:smile: 我一开始以为是服务器多次接收，原来是\r\n的原因，是我没看懂代码，表达不准确:blush:，该我谢谢你啊，多谢支持。:+1:
