### ISSUE TITLE
API封装得很漂亮！加油！

### ISSUE THREAD

**Issue by huge818** [hongliuliao/ehttp#8]
API封装得很漂亮！加油！
看到这个库，很简洁，感觉有抛弃nodejs的冲动了。
希望继续加油，完善！
如果能支持多平台，支持mingw编译就更好了。

**Comment by hongliuliao** [comment]
谢谢, 其实readme中有说明, 项目有参考restbed, 你可以看看 [restbed](https://github.com/Corvusoft/restbed) 是否能满足你的要求. ehttp的设计目标在短期内还是保持轻量级
